server:
    port: 8080
spring:
    datasource:
        url: jdbc:h2:../DataBase/banco;DB_ClOSE_ON_EXIT=FALSE
        username: bancofiap
        password: bancofiap
    mvc:
      pathmatch:
            matching-strategy: ANT_PATH_MATCHER
